project:
  appkey: framework-mongo
  info: OMG,Elasticsearch project runs successfully！

#默认配置
spring:
  profiles:
    active: @profileActive@

debug: false

server:
  port: 8080

---
#dev环境
spring:
  profiles: dev

---
#test环境
spring:
  profiles: test

---
#prod环境
spring:
  profiles: prod


